export const MATRIX_CREATED = 'MATRIX_CREATED';
export const GAME_OVER = 'GAME_OVER';
export const SHOW_NEW_GAME_DIALOG = 'SHOW_NEW_GAME_DIALOG';
export const SHOW_CUSTOM_GAME_DIALOG = 'SHOW_CUSTOM_GAME_DIALOG';
export const CELL_EXPOSED = 'CELL_EXPOSED';
export const EMPTY_CELL_EXPOSED = 'EMPTY_CELL_EXPOSED';
